### PR TITLE
Allow option to manually install CRDs.

### PR DESCRIPTION
**Pull request by krodyrobi**
# Pull Request Template

## Prerequisites

Issue: #337 

## Motivation

Allow CRDs to be installed separately so that helm / kubernetes validations can be applied without installation. 

## Approach

The PR leaves the default behaviour in place, only those that opt in will not get the CRDs installed.
During release a new artifact will be bundled `crd.yml` for download by clients.

## Pull Request status

* [x] Initial implementation

## Third-party code
N/A

### CODE REVIEW

**Comment by kerenlahav** [comment]
I did not understand the changes in the makefile and the release.yml.
why not just wrap the crd.yml as you did and use the installCRDs value from the values.yaml?

**Comment by krodyrobi** [comment]
@kerenlahav @TalShorSap 

- controller needs new crd definitions -> code annotated with kubebuilder syntax
- kubebuilder reads go code -> generates `config/crd/bases` files
- on release helm-charts make command applies kustomise from `config/crd/bases` -> saves output under `sapbtp-operator-charts/templates/crd.yml` replacing the existing file (git release has content hardcoded but release has another possibly newer version)
- the chart is deployed to chart repository with new crd.yml file

Cannot change `sapbtp-operator-charts/templates/crd.yml` this file's content gets replaced completely on release.
Cannot change `config/crd/bases` as these are generated from code so on new run of kubebuilder all changes get lost (even if this would not be a thing helm template syntax is not supported by kustomise)

The make code basically states that when issue-ing a helm-charts command you can either get helm **wrapped output or not** stored at a given file location (by default if wrapped and stored in helm chart, with the if evaluating to true, so helm still generates and manages the crds)

The unwrapped output is to be used by `kubectl apply -f <repo_url>/release/version/<>/crd.yml` and is always deployed as a separate file on release to allow people that set "false in values.yaml" to still get crd definitions, here helm template syntax is not supported as this file is ran out of helm.

This is why I said I don't get why you guys use templates for templates, but c'est la vie

**Comment by kerenlahav** [comment]
@krodyrobi 
you can use the helm upgrade to install the crds (use the same version but set the installCRDs flag to true), it will only apply the crd.yml
if you want to apply it manually don't use the crd.yml located in the helm chart
https://github.com/SAP/sap-btp-service-operator/blob/4801433595006e3face5418171f78f990519acc3/config/crd/bases/services.cloud.sap.com_servicebindings.yaml

**Comment by krodyrobi** [comment]
@kerenlahav
Yes this is exactly what the PR does it publishes the helm chart with the if checks for installCRDs AND it exposes the joined files that generated the crd.yaml as a separate artifact with a release version.

kubectl apply -f only works with a single URL pointing to a file not to a directory.

[cert-manager approach installation and considerations](https://cert-manager.io/docs/installation/helm/#helm-installation)

**Pull request closed without merging**
