### PR TITLE
support long binding names

### PR DESCRIPTION
**Pull request by kerenlahav**
# Pull Request Template

## Prerequisites

* If there is no issue related to your pull request - open one and assign yourself to it. If you're proposing a solution to an already opened issue - simply assign yourself to it.

## Motivation

*Describe the problem you're trying to solve or the feature you're proposing in addition to a link to the related issue.*

## Approach

_How does this change address the problem?_

## Pull Request status

* [x] Initial implementation
* [ ] Refactoring
* [ ] Unit tests
* [ ] Integration tests

Feel free to construct the checklist with whatever items seem most reasonable for your change. You could disassemble the Implementation part to even smaller separate checklist items if you're working on something big for example. But do make the effort to provide a checklist of some sort so that the core team as well as the community can have an idea about the progress of your Pull Request.

## Third-party code

If you use third party code with your contribution such as, components, libraries, or snippets make sure to mention that.

## Work in Progress label

For as long as development of your Pull Request is still ongoing you MUST label it with a **wip** label as well as prefix the name of the PR with *[WIP]*.

For example: *[WIP] Service brokers API*

### CODE REVIEW

**Comment by c0d1ngm0nk3y** [comment]
Isn't that the same as #186? Why opening another one?

**Comment by kerenlahav** [comment]
> Isn't that the same as #186? Why opening another one?
I was not able to edit the original PR.
added test
ןא  שI

**Review by evyaffe — APPROVED** [review]

**Comment by c0d1ngm0nk3y** [comment]
@kerenlahav Are there any plans to release this? We are facing the same issues and realized there were no new releases since June.

**Comment by kerenlahav** [comment]
https://github.com/SAP/sap-btp-service-operator/releases/tag/v0.2.8
Thanks

**Pull request merged**
